# Generated by Django 4.0.5 on 2022-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('auto', 'Автомобили'), ('service', 'Услуги'), ('sport', 'Спорт'), ('education', 'Образование')], default='auto', max_length=50, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
