# Generated by Django 4.0.5 on 2022-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_advertisement_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
